name: Push site to the gh-pages branch
on: 
  push:
    branches:
      - main
      - try-docusaurus-script
permissions:
  contents: write
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cache node_modules
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Build site
      env:
      - DEPLOYMENT_BRANCH=main
      - GIT_USER=kebetsi
      run: |
        yarn install --frozen-lockfile
        yarn deploy
